# Generated by Django 4.2.13 on 2024-06-13 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='birthday',
            field=models.DateField(db_column='Birthday', verbose_name='生日'),
        ),
    ]
